# Generated by Django 5.1.1 on 2024-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bill_title', models.CharField(blank=True, max_length=255)),
                ('bill_summary', models.TextField(blank=True, null=True)),
                ('bill_link', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_have_read', models.CharField(choices=[('Have read', 'Have read'), ('Have not read', 'Have not read')], max_length=255)),
                ('weather_agree', models.CharField(choices=[('Agree', 'Agree'), ('Not agree', 'Not agree')], max_length=255)),
                ('user_opinion', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
