# Generated by Django 5.1.1 on 2024-10-01 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_participation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='bill_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill_participation.bill'),
        ),
    ]
