# Generated by Django 5.1.1 on 2024-10-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_participation', '0002_opinion_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
