# Generated by Django 5.1.1 on 2024-10-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_participation', '0004_remove_opinion_weather_agree_opinion_weather_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='weather_have_read',
            new_name='whether_have_read',
        ),
        migrations.RenameField(
            model_name='opinion',
            old_name='weather_support',
            new_name='whether_support',
        ),
    ]
