# Generated by Django 5.1.1 on 2024-10-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_participation', '0005_rename_weather_have_read_opinion_whether_have_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='whether_have_read',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('explained to by someone', 'Explained to by someone')], max_length=255),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='whether_support',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('need amendment', 'Need Amendment')], max_length=255, null=True),
        ),
    ]
