# Generated by Django 5.1.1 on 2024-10-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_participation', '0007_issue_remove_opinion_bill_no_opinion_bill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='bill',
            new_name='issue',
        ),
    ]
