# Generated by Django 5.1.1 on 2024-10-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_participation', '0008_rename_bill_opinion_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='issue',
            new_name='issue_id',
        ),
    ]
