# Generated by Django 5.1.1 on 2024-10-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_participation', '0009_rename_issue_opinion_issue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='hashed_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
